name: tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    services:
      mysql:
        image: mysql/mysql-server:8.0
        env:
          MYSQL_ROOT_HOST: '%'
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-composer-${{ hashFiles('composer.lock') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: json, dom, curl, libxml, mbstring, zip
          tools: composer:v2
          coverage: none

      - name: Setup node env
        uses: actions/setup-node@v4
        with:
          node-version: 22
          check-latest: true
          cache: 'yarn'

      - name: Copy example .env
        run: cp .env.example .env

      - name: Install PHP dependencies
        run: composer install --no-interaction --no-progress --ansi

      - name: Generate application key
        run: php artisan key:generate

      - name: Install yarn dependencies
        run: yarn install

      - name: Build frontend
        run: yarn build

      - name: Run tests
        run: composer test
        env:
          DB_PASSWORD: password

#      - name: Deploy staging
#        if: github.ref_name == 'main'
#        run: curl ${{ secrets.FORGE_STAGING_HOOK }}
